### ISSUE TITLE
react-typescript template has inconsistent line endings

### ISSUE THREAD

**Issue by samiskin** [electron-userland/electron-forge-templates#12]
On a Macbook, running:

```
electron-forge init my-forge-project --template=react-typescript
cd my-forge-project
git add .
git diff --cached
```

Shows that the following files have CRLF line endings:
```
.compilerc
src/app.tsx
src/index.html
src/index.ts
tsconfig.json
tslint.json
```

While the following file has LF line endings:
```
package.json
.gitignore
```

**Comment by malept** [comment]
Related info: https://github.com/electron-userland/electron-forge-templates/pull/13#issuecomment-280894432

At this point, it may either be the NPM package or something *really* weird in the Electron Forge initialization code.

**Comment by samiskin** [comment]
`npm install electron-forge-template-react-typescript` adds files with `^M`s so it was probably just published from a windows machine and `npm publish` doesn't convert the line endings

**Comment by anaisbetts** [comment]
> npm install electron-forge-template-react-typescript adds files with ^Ms so it was probably just published from a windows machine and npm publish doesn't convert the line endings

This is most likely the case

**Comment by malept** [comment]
Is this still the case or was this resolved?

**Comment by samiskin** [comment]
Looks like its still there.  I updated to electron-forge 3.0.5 and ran the test case I mentioned in the issue description, and the same files had the line endings I described earlier.

**Comment by malept** [comment]
I released a new version of the react-typescript template to NPM (I run Linux) and I verified that using the new version doesn't create projects with Windows line endings.
