### ISSUE TITLE
Angular 2 Template not working

### ISSUE THREAD

**Issue by bjines** [electron-userland/electron-forge-templates#19]
Running the command
`electron-forge init <project name> --template=angular2`
And, this runs successfully, but when I run 
`electron-forge start`
In the newly created project, I get an error from the bootstrap.ts:
> Uncaught ReferenceError: exports is not defined

**Comment by malept** [comment]
Can you get a backtrace?

**Comment by bartcich** [comment]
Pin typescript to 2.1.x as in my PR: #16 (change package.json). After that run:
`npm install`

**Comment by bjines** [comment]
Thanks, forgot to look through the PR as well as issues first...

**Comment by malept** [comment]
The fix is released in 1.0.3.
