### ISSUE TITLE
Angular2 Template app doesn't start

### ISSUE THREAD

**Issue by zorro2b** [electron-userland/electron-forge-templates#24]
I created an app using the angular2 template, made no further changes and it would not run correctly.
The console shows this error:
Uncaught ReferenceError: exports is not defined
at bootstrap.ts:2

I created a vanilla es6 app and that worked fine.

**Comment by juarezpaf** [comment]
I'm facing the same issue over here
<img width="1280" alt="electron-forge-template-angular2-bug" src="https://cloud.githubusercontent.com/assets/21221/23829559/a6ea6550-06d3-11e7-892c-014171b725eb.png">

**Comment by MarshallOfSound** [comment]
@zorro2b @juarezpaf Running `npm i -g electron-forge` again should bring in the udpated version of the angular 2 template 👍

**Comment by juarezpaf** [comment]
@MarshallOfSound thanks a lot. 🚀
