### ISSUE TITLE
Serious security issues

### ISSUE THREAD

**Issue by khawarizmus** [electron-userland/electron-forge-templates#30]
running an `nsp` check before starting my project give me this report:

![security report](http://i.imgur.com/MQMHzAl.png)

more information about [nsp](https://nodesecurity.io/)

How to fix this?
Can i just upgrade the packages mentioned by `nsp` ?

**Comment by MarshallOfSound** [comment]
Neither of these modules are a problem as they are development dependencies, the code mentioned by NSP is never included in a production build and therefore there is no security issue here 👍
