### ISSUE TITLE
Angular app-routing causes electron-compile to fail : "Can't stat"

### ISSUE THREAD

**Issue by nphias** [electron-userland/electron-forge-templates#33]
* [x ] I have read the [contribution documentation](https://github.com/electron-userland/electron-forge-templates/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

I created an electron forge project with template angular 2
i then added an app router to my app-module with an empty path matcher. this causes a fail to compile stat problem where stat is based on a directory not a file.
```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

export const routes: Routes = [
  { path: '', redirectTo: '/music', pathMatch: 'full'}
  //{ path: 'lazy', loadChildren: 'app/lazy/lazy.module#LazyModule' }
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule {}
```

```
Put the console output here
```
Failed to compile .../src/music: Can't stat ../src/music
Error: Can't stat .../src/music
    at .../node_modules/electron-compile/lib/file-change-cache.js:183:42
    at Generator.next (<anonymous>)
    at step (.../node_modules/electron-compile/lib/file-change-cache.js:27:191)
    at .../node_modules/electron-compile/lib/file-change-cache.js:27:361

**What command line arguments are you passing?**

```
none
```

**What does your `config.forge` data in `package.json` look like?**

```
unchanged from default
```

this I suspect will be the experience of others who want to use electron, angular and basic routing

**Comment by anaisbetts** [comment]
Is `../src/music` a real folder that exists? It seems like Angular is trying to do something Clever here.

**Comment by nphias** [comment]
yes, its a real folder that exists.

**Comment by ebordon** [comment]
Have you added  `<base href="./">` in head section of index.html file?

You might need to add   `<router-outlet></router-outlet>` in your appComponent template.

BTW. I had many problems with routes in my electron-forge app and I solved them by updating to the last angular version (currently 4.x.x)

**Comment by PhoneixS** [comment]
Moved the comment to https://github.com/electron-userland/electron-compile/issues/233#issuecomment-447919791, I think it belongs more to that issue.

**Comment by malept** [comment]
Closing, see https://github.com/electron-userland/electron-forge-templates/issues/66
