### ISSUE TITLE
VSCode Debug: Template - React & Typescript

### ISSUE THREAD

**Issue by mtompkins** [electron-userland/electron-forge-templates#34]
* [ ] I have read the [contribution documentation](https://github.com/electron-userland/electron-forge-templates/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

Referencing: https://github.com/electron-userland/electron-forge#debugging-your-application-through-vs-code

The initial spin-up prior to any modifications does not include (in the ../bin directory):
- electron-forge-vscode-nix
- electron-forge-vscode-win.cmd

so attaching and debugging fails following the reference.

**Console output when you run `electron-forge init` with the environment variable `DEBUG=electron-forge:*`. (Instructions on how to do so [here](https://www.npmjs.com/package/debug#usage)). Please include the stack trace if one exists.**

```
Put the console output here
```

**What command line arguments are you passing?**

```
Put the arguments here
```

**What does your `config.forge` data in `package.json` look like?**

```
Paste the config.forge JSON object here
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem.**

**Comment by MarshallOfSound** [comment]
@mtompkins The default templates do not install `electron-forge` itself as a dependency so those executables do not exist.  You would need to `npm i electron-forge` locally to get the `forge` and and other executables locally.

Assuming forge is installed globally those debug commands should be available on your path so you can remove the local node modules path to the executable completely and it will work.

**Comment by mtompkins** [comment]
Thanks for the quick reply @MarshallOfSound - it was more of an informational that the documentation is a bit misleading.

**Comment by MarshallOfSound** [comment]
@mtompkins Fair enough, I'll add a bit to indicate that you need electron forge installed locally for those scripts to exist 👍
