### ISSUE TITLE
[request] Add Inferno template

### ISSUE THREAD

**Issue by ghost** [electron-userland/electron-forge-templates#40]
Could we have an [inferno](https://github.com/infernojs/inferno) template for `electron-forge`?

I'm not sure exactly where to start to make one, if someone could point me in the right direction that would be great. 👍

**Comment by malept** [comment]
There's some instructions here: https://github.com/electron-userland/electron-forge/wiki/Custom-template-modules

That wiki page should probably move to this repo.

**Comment by ghost** [comment]
Awesome, thanks! Would you be happy for a PR with the template once I get it complete?

**Comment by malept** [comment]
Would you be willing to maintain the template?

**Comment by ghost** [comment]
Yeah, of course 👍 

[This is it here](https://github.com/callodacity/electron-forge-template-inferno). I've just tested it and it seems to work alright. If you're happy with that I'll draft up a PR at some point today.

**Comment by malept** [comment]
I mean, if you already have your own repository for it and you're willing to maintain it, it's quite all right to leave it there. You'd have control over the NPM module as well.

**Comment by ghost** [comment]
Right, I see what you mean. That's fine with me. 👌

I was just doing this so that if others went looking for it they'd find it on [electron-forge-templates](https://github.com/electron-userland/electron-forge-templates) or perhaps https://beta.electronforge.io/templates in the future. (Or,  maybe adding it to the README of this repo?).

In any case, I think we should add https://github.com/electron-userland/electron-forge/wiki/Custom-template-modules to the readme, or make a wiki page for it here.

**Comment by malept** [comment]
I'm OK with adding a wiki page for third party Forge templates.
