### ISSUE TITLE
React HMR doesn't work consistently

### ISSUE THREAD

**Issue by walleXD** [electron-userland/electron-forge-templates#41]
When changes are made to a file and saved, HMR works the first time but if further changes are made to the same file, there is not HMR to reflect the newer changes but HMR works if a different file is changed.

Any ideas about how to fix this? I am using the js react template

**Comment by MarshallOfSound** [comment]
See https://github.com/electron/electron-compile/issues/237

Unfortunately this has never happened to me so I have zero clue what's going on and if I can't replicate it I can't even begin to think about fixing it 😆

**Comment by walleXD** [comment]
@MarshallOfSound I figured it out, at least for my case..... its webstorm. After testing multiple test instance projects, it seems that when I save in atom, multiple saves lead to multiple reloads but that isn't the case when I save it webstrom. Don't know what's up with webstorm, but i think I am gonna stick with atom for now. Thanks a bunch @MarshallOfSound 👍
