### ISSUE TITLE
Visual Studio 2015 Guide

### ISSUE THREAD

**Issue by schodemeiss** [electron-userland/electron-forge-templates#52]
The documentation about getting any of the TypeScript templates and a fulling running and building system in Visual Studio 2015 (or 2013 or 2017) appear a little sparse.

There's lots of documentation about VSCode, but nothing about actual Visual Studio.

Can we get some documentation about how to create a project in the popular IDE?

Thanks!

**Comment by malept** [comment]
Closing, see https://github.com/electron-userland/electron-forge-templates/issues/66
