### ISSUE TITLE
Sass: Imported partials not recompiling on change

### ISSUE THREAD

**Issue by zakcutner** [electron-userland/electron-forge-templates#55]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-forge-templates/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

I am trying to use Sass's `@import` in order to keep variables across multiple Sass files. I have a `_variables.scss` file as follows:

```sass
$colour: #000;
```

I then have an `index.scss` file, in the same directory, in which I would like to use this variable in the following way:

```sass
@import "variables";
    
body {
    background: $colour;
}
```

I then can import my `index.scss` file in `index.html` like so (both sass files are in the `styles` folder):

```html
<link rel="stylesheet" href="styles/index.scss">
```

This works and the background becomes black. The problem arises however when I change the `_variables.scss` file to be this for example:

```sass
$colour: #fff;
```

The background doesn't update to become white in this case.

The issue is essentially that changes to Sass partial files are not refleced when their contents are changed. Updates are quite alright with regular files not beginning with an underscore like `index.scss`.

It may be worth noting that I see the following message when running my app in the debug mode:

```
electron-forge:hook could not find hook: generateAssets +0ms
```

I hope this is all clear, many thanks in advance!

**Comment by zippoxer** [comment]
Can reproduce.

**Comment by malept** [comment]
Closing, see https://github.com/electron-userland/electron-forge-templates/issues/66
