### ISSUE TITLE
Typescript Paths

### ISSUE THREAD

**Issue by miguelramos** [electron-userland/electron-forge-templates#57]
* [ ] I have read the [contribution documentation](https://github.com/electron-userland/electron-forge-templates/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
Current typescript doesn't support paths options. Is there any special config to use it?
I've use the angular template to generate the project.

![image](https://user-images.githubusercontent.com/495720/41168130-f4cb1ac0-6b3c-11e8-967d-5e66bc9e526d.png)

TsConfig:

![image](https://user-images.githubusercontent.com/495720/41168197-1ec99b30-6b3d-11e8-99f3-7ba0376d7862.png)

**Console output when you run `electron-forge init` with the environment variable `DEBUG=electron-forge:*`. (Instructions on how to do so [here](https://www.npmjs.com/package/debug#usage)). Please include the stack trace if one exists.**

```
Put the console output here
```
![image](https://user-images.githubusercontent.com/495720/41168095-da0ad72a-6b3c-11e8-8e6a-ce1f7fc85faa.png)

**What command line arguments are you passing?**

```
Put the arguments here
```

**What does your `config.forge` data in `package.json` look like?**

```
"config": {
    "forge": {
      "make_targets": {
        "win32": [
          "squirrel"
        ],
        "darwin": [
          "zip"
        ],
        "linux": [
          "deb",
          "rpm"
        ]
      },
      "electronPackagerConfig": {
        "packageManager": "yarn"
      },
      "electronWinstallerConfig": {
        "name": "forge_angular"
      },
      "electronInstallerDebian": {},
      "electronInstallerRedhat": {},
      "github_repository": {
        "owner": "",
        "name": ""
      },
      "windowsStoreConfig": {
        "packageName": "",
        "name": "forgeangular"
      }
    }
  },
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem.**

**Comment by malept** [comment]
Closing, see https://github.com/electron-userland/electron-forge-templates/issues/66
