### ISSUE TITLE
`babel-preset-react` included with project initiated via `vue` template

### ISSUE THREAD

**Issue by vintprox** [electron-userland/electron-forge-templates#59]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-forge-templates/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

You'll eventually find it not appropriate to have `babel-preset-react` module when initializing a project via `vue` template.

**Please provide either a failing minimal testcase or detailed steps to
reproduce your problem.**

```
electron-forge init project-name --template=vue
cd project-name
nano package.json
```

**Comment by malept** [comment]
Closing, see https://github.com/electron-userland/electron-forge-templates/issues/66
