### ISSUE TITLE
Add ESLint support for Vue.js templates

### ISSUE THREAD

**Issue by malept** [electron-userland/electron-forge-templates#9]
From @Calinou in https://github.com/electron-userland/electron-forge/issues/132

We would need to figure out what are the "appropriate" ESLint plugins for a generic Vue.js project.

**Comment by vintprox** [comment]
It'll be sweet to see it implemented!

**Comment by malept** [comment]
Closing, see https://github.com/electron-userland/electron-forge-templates/issues/66
